<?php

namespace AppBundle\Repository;

/**
 * MitarbeiterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MitarbeiterRepository extends \Doctrine\ORM\EntityRepository
{
}
