app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Frontend der Anwendung im webController definiert!
homepage:
    path:     /
    defaults: { _controller: AppBundle:Website:homepage }

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Website:contact }

sign_in:
    path:     /sign_in
    defaults: { _controller: AppBundle:Website:sign_in }

# Backend der Anwendung definiert!

dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Website:dashboard }

# Todo´s-Application

todo_index:
    path:     /dashboard/todos
    defaults: { _controller: AppBundle:Todo:index }

todo_create:
    path:     /dashboard/todos/create
    defaults: { _controller: AppBundle:Todo:create }

todo_edit:
    path:     /dashboard/todos/edit/{id}
    defaults: { _controller: AppBundle:Todo:edit }

todo_details:
    path:     /dashboard/todos/details/{id}
    defaults: { _controller: AppBundle:Todo:details }

todo_delete:
    path:     /dashboard/todos/delete/{id}
    defaults: { _controller: AppBundle:Todo:delete }

# Anmeldebereich! Teststatus

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:index }

# Newsseite zum Üben, warten auf Sven´s Aufgaben! Funktioniert!

news_index:
    path:     /dashboard/news
    defaults: { _controller: AppBundle:News:index }

news_create:
    path:     /dashboard/news/erstellen
    defaults: { _controller: AppBundle:News:create }

#Mitarbeiter

employee_index:
    path:     /dashboard/employee
    defaults: { _controller: AppBundle:Employee:index }

employee_create:
    path:     /dashboard/employee/create
    defaults: { _controller: AppBundle:Employee:create }

employee_edit:
    path:     /dashboard/employee/edit/{id}
    defaults: { _controller: AppBundle:Employee:edit }

employee_details:
    path:     /dashboard/employee/details/{id}
    defaults: { _controller: AppBundle:Employee:details }

employee_delete:
    path:     /dashboard/employee/delete/{id}
    defaults: { _controller: AppBundle:Employee:delete }

# Finanzen

finance_index:
    path:     /dashboard/finance
    defaults: { _controller: AppBundle:Finance:index }

# Projekte

project_index:
    path:     /dashboard/project
    defaults: { _controller: AppBundle:Project:index}

# Kunden

customer_index:
    path:     /dashboard/customer
    defaults: { _controller: AppBundle:Customer:index}



